apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-depl
spec:
    replicas: 1 #number of pods
    selector:
        matchLabels: # find all pods with label 'auth'
            app: auth
    template:
        metadata:
            labels: #labels pods being created (matches matchLabels)
                app: auth
        spec:
            containers:
                - name: auth
                  image: landen1221/auth
---
apiVersion: v1
kind: Service
metadata:
    name: auth-srv
spec:
    selector:
        app: auth
    type: ClusterIP
    ports:
        - name: auth
          protocol: TCP
          port: 3000
          targetPort: 3000
